CREATE TABLE roles_tb
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles_tb PRIMARY KEY (role_id)
);

CREATE TABLE user_role
(
    id_user_role BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      UUID                                    NOT NULL,
    role_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id_user_role)
);

CREATE TABLE users_tb
(
    user_id       UUID         NOT NULL,
    username      VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    birthday_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    age           INTEGER      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    password      VARCHAR(255) NOT NULL,
    user_active   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users_tb PRIMARY KEY (user_id)
);