CREATE TABLE token_tb
(
    token_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token         VARCHAR(512)                            NOT NULL,
    is_logged_out BOOLEAN                                 NOT NULL,
    user_id       UUID                                    NOT NULL,
    CONSTRAINT pk_token_tb PRIMARY KEY (token_id)
);