CREATE TABLE chats_tb
(
    chats_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    title      VARCHAR(225)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_chats_tb PRIMARY KEY (chats_id)
);

CREATE TABLE messages_tb
(
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chats_id   BIGINT                                  NOT NULL,
    content    TEXT                                    NOT NULL,
    create_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_messages_tb PRIMARY KEY (message_id)
);